### ISSUE TITLE
node-gyp rebuild error 

### ISSUE THREAD

**Issue by abkava** [bigmlcom/bigml-node#101]
error while installing module
OS: ubuntu 17.04
Node: v8.2.1
Npm : 3.10.10

Linux 4.8.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "bigml" "--save"
npm ERR! node v8.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.17.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.17.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

**Comment by mmerce** [comment]
Sorry for the late reply. This seems to be a known issue and can be related to the node install (or some of its modules), as the message suggests. Please, check the following links for suggestions to solve the problem:

https://github.com/lovell/sharp/issues/517
https://github.com/lovell/sharp/issues/643
https://github.com/lovell/sharp/issues/759
